-- ============================================================================
-- Fase 2: ordens de produção (OP) com cálculo automático
-- ============================================================================

create table if not exists public.ordens_producao (
  id uuid primary key default gen_random_uuid(),
  numero integer generated by default as identity unique,
  peca_id uuid not null references public.pecas (id),
  maquina_id uuid not null references public.maquinas (id),
  quantidade_planejada numeric(12, 4) not null check (quantidade_planejada > 0),
  tempo_estimado_minutos numeric(14, 4) not null,
  status text not null default 'aberta'
    check (status in ('aberta', 'em_producao', 'parada', 'concluida')),
  criado_por uuid references public.operadores (id),
  created_at timestamptz not null default now(),
  concluida_em timestamptz
);

comment on column public.ordens_producao.status is
  'aberta = gerada mas sem apontamento aberto no momento (inclui pos-stop parcial); em_producao / parada / concluida conforme regras de negocio.';

-- só pode existir 1 OP "ativa" (em_producao ou parada) por máquina ao mesmo tempo
-- — trava de recurso exclusivo (regra 6), garantida no nível do banco.
create unique index if not exists ordens_producao_maquina_ativa_idx
  on public.ordens_producao (maquina_id)
  where status in ('em_producao', 'parada');

create index if not exists ordens_producao_status_idx on public.ordens_producao (status);

alter table public.ordens_producao enable row level security;

create policy "op_select_autenticados" on public.ordens_producao
  for select to authenticated using (true);

create policy "op_insert_gestor" on public.ordens_producao
  for insert to authenticated with check (public.is_gestor());

create policy "op_update_gestor" on public.ordens_producao
  for update to authenticated using (public.is_gestor()) with check (public.is_gestor());

alter publication supabase_realtime add table public.ordens_producao;
